//Game Status
int WAITING_FOR_PLAYERS = 0;
int STARTING = 1;
int ASK_FOR_COMMANDS = 2;
int WAITING_FOR_COMMANDS = 3;
int PROCESSING_COMMANDS = 4;
int SENDING_GAMEDATA = 5;
int WAIT_FOR_TERMINALS = 6;
int FINISHED = 7;